---
title: "Highly Adaptive Lasso and Targeted Learning 📿🎯"
subtitle: "Short course"
author: "Mark van der Laan (UC Berkeley) and Sky Qiu (UC Berkeley)" 
date: last-modified 
format: html
---

## Welcome to the short course!

This page contains slides and code examples for the short course on Highly Adaptive Lasso and Targeted Learning at the DahShu Data Science Symposium 2025.

## Schedule

Here is the schedule for the day (9am-5pm, October 18th, 2025):

+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time**        | **Topic**                                                                                                               | **Links to materials**                                                                                                                                                     |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9am-10.20am     | Introduction to Targeted Learning; The Roadmap; Super Learning; TMLE                                                    |                                                                                                                                                                            |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10.20am-10.40am | Coffee/Tea break, Q&A                                                                                                   |                                                                                                                                                                            |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10.40am-12pm    | Introduction to Highly Adaptive Lasso: cadlag functions, zero-order spline HAL, rate of convergence, `hal9001` software | -   `hal9001` [\[vignette\]](https://tlverse.org/hal9001/articles/intro_hal9001.html)                                                                                      |
|                 |                                                                                                                         | -   Introduction to `hal9001` \[TODO\]                                                                                                                                     |
|                 |                                                                                                                         | -   Estimating conditional average treatment effects [\[code example\]](cate.qmd)                                                                                          |
|                 |                                                                                                                         | -   Estimating conditional densities [\[code example\]](cde.qmd)                                                                                                           |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12pm-1pm        | Lunch break                                                                                                             |                                                                                                                                                                            |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1pm-2.20pm      | Higher order splines, examples of 1st and 2nd order HAL, rate of convergence, HAL-TMLE                                  | -   Examples of the k-th order spline representation: [\[k=1, d=3\]](k1d3.qmd), [\[k=2, d=3\]](k2d3.qmd)                                                                   |
|                 |                                                                                                                         | -   Specifying a diverse super learner library including different specifications (smoothness orders, subspaces) of candidate HAL learners [\[code example\]](hal_dsl.qmd) |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.20pm-2.30pm   | Coffee/Tea break, Q&A                                                                                                   |                                                                                                                                                                            |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2.30pm-3.30pm   | HAL-based adaptive-TMLE, applications to RCT-RWD hybrid designs                                                         | -   Adaptive-TMLE for augmenting an RCT with external RWD [\[code example\]](atmle.qmd)                                                                                    |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.30pm-3.40pm   | Coffee/Tea break, Q&A                                                                                                   |                                                                                                                                                                            |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3.40pm-4.40pm   | L-TMLE, new advancements in TMLE: Deep L-TMLE, Profile-TMLE                                                             | -   Estimating effect of counterfactual treatment regimes in longitudinal data with `ltmle` [\[code example\]](ltmle.qmd)                                                  |
|                 |                                                                                                                         | -   DeepLTMLE example \[TODO\]                                                                                                                                             |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4.40pm-5pm      | Closing remarks, Q&A                                                                                                    |                                                                                                                                                                            |
+-----------------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Environment setup

-   R (≥ 4.3) installed.
-   Recommended IDE: RStudio.
-   R packages required:

```{r, eval=FALSE}
# install CRAN packages
cran_pkgs <- c("hal9001", "glmnet", "plotly", "haldensify", "origami", "tmle",
               "MASS", "ggplot2", "dbarts", "xgboost", "ltmle")
missing_cran <- cran_pkgs[!(cran_pkgs %in% installed.packages()[, "Package"])]
if (length(missing_cran) > 0) {
  install.packages(missing_cran)
}

# install GitHub packages
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
github_pkgs <- c("tlverse/sl3", "tq21/atmle")
for (pkg in github_pkgs) {
  pkg_name <- basename(pkg)
  if (!requireNamespace(pkg_name, quietly = TRUE)) {
    remotes::install_github(pkg)
  }
}
```

## Relevant books/papers for this short course

-   van der Laan, Mark and Sherri Rose (2011) Targeted Learning: Causal Inference for Observational and Experimental Data. *Springer Science & Business Media*. [\[Link\]](https://link.springer.com/book/10.1007/978-1-4419-9782-1)

-   van der Laan, Mark and Sherri Rose (2018) Targeted Learning in Data Science: Causal Inference for Complex Longitudinal Studies. *Springer Science & Business Media*. [\[Link\]](https://link.springer.com/book/10.1007/978-3-319-65304-4)

-   Petersen, Maya and Mark van der Laan (2014) "Causal models and learning from data: integrating causal modeling and statistical estimation." *Epidemiology* 25, no. 3: 418-426. [\[Link\]](https://journals.lww.com/epidem/abstract/2014/05000/causal_models_and_learning_from_data__integrating.13.aspx)

-   Dang, Lauren et al (2023). "A causal roadmap for generating high-quality real-world evidence." *Journal of Clinical and Translational Science*, 7(1), p. e212. doi:10.1017/cts.2023.635. [\[Link\]](https://www.cambridge.org/core/journals/journal-of-clinical-and-translational-science/article/causal-roadmap-for-generating-highquality-realworld-evidence/3F30968E70E7A13EE7FC41A46A8C3AAD)

-   van der Laan, Mark, Eric Polley, and Alan Hubbard (2007). "Super learner." *Statistical applications in genetics and molecular biology*, 6, Article25. https://doi.org/10.2202/1544-6115.1309 [\[Link\]](https://www.degruyterbrill.com/document/doi/10.2202/1544-6115.1309/html)

-   van der Laan, Mark and Daniel Rubin (2006). "Targeted Maximum Likelihood Learning." *The International Journal of Biostatistics*, vol. 2, no. 1. [\[Link\]](https://www.degruyterbrill.com/document/doi/10.2202/1557-4679.1043/html)

-   van der Laan, Mark (2017). "A generally efficient targeted minimum loss based estimator based on the highly adaptive lasso." *The international journal of biostatistics*. [\[Link\]](https://www.degruyterbrill.com/document/doi/10.1515/ijb-2015-0097/html)

-   Benkeser, David, and Mark van der Laan. "The highly adaptive lasso estimator." *2016 IEEE international conference on data science and advanced analytics (DSAA).* IEEE, 2016. [\[Link\]](https://pmc.ncbi.nlm.nih.gov/articles/PMC5662030/)

-   van der Laan, Mark. "Higher order spline highly adaptive lasso estimators of functional parameters: Pointwise asymptotic normality and uniform convergence rates." arXiv preprint arXiv:2301.13354 (2023). [\[Link\]](https://arxiv.org/abs/2301.13354)

-   van der Laan, Lars, Marco Carone, Alex Luedtke, and Mark van der Laan. "Adaptive debiased machine learning using data-driven model selection techniques." arXiv preprint arXiv:2307.12544 (2023). [\[Link\]](https://arxiv.org/abs/2307.12544)

-   van der Laan, Mark, Sky Qiu, Jens Tarp, and Lars van der Laan. "Adaptive-TMLE for the average treatment effect based on randomized controlled trial augmented with real-world data." arXiv preprint arXiv:2405.07186 (2024). [\[Link\]](https://arxiv.org/abs/2405.07186)

-   Qiu, Sky, Jens Tarp, Andrew Mertens, and Mark van der Laan. "An estimator-robust design for augmenting randomized controlled trial with external real-world data." arXiv preprint arXiv:2501.17835 (2025). [\[Link\]](https://arxiv.org/abs/2501.17835)

-   Shirakawa, Toru, Yi Li, Yulun Wu, Sky Qiu, Yuxuan Li, Mingduo Zhao, Hiroyasu Iso, and Mark van der Laan. "Longitudinal targeted minimum loss-based estimation with temporal-difference heterogeneous transformer." *Proceedings of the 41st International Conference on Machine Learning*, PMLR 235:45097-45113 (2024). [\[Link\]](https://arxiv.org/abs/2404.04399)

## Additional resources

-   Center for Targeted Machine Learning and Causal Inference at Berkeley: <https://ctml.berkeley.edu/>

-   Introduction to causal inference by Maya Petersen and Laura Balzer: <https://ctml.berkeley.edu/introduction-causal-inference>

-   Targeted Learning in R: Causal Data Science with the tlverse Software Ecosystem (tlverse handbook): <https://tlverse.org/tlverse-handbook/>

-   Kat Hoffman's blog and tutorial on Targeted Learning: <https://www.khstats.com/blog/tmle/tutorial>

-   Check out [TL Revolution's YouTube channel](https://www.youtube.com/@putnamdatasciences1309/videos) for FDA funded webinar series on Targeted Learning:

::: {style="max-width: 480px; margin: auto;"}
{{< video https://www.youtube.com/watch?v=PrPNP5RVcLg >}}
:::

::: {style="max-width: 480px; margin: auto;"}
{{< video https://www.youtube.com/watch?v=8Q9dfW3oOi4 >}}
:::

::: {style="max-width: 480px; margin: auto;"}
{{< video https://www.youtube.com/watch?v=ANuvSrkJ3Ag >}}
:::

::: {style="max-width: 480px; margin: auto;"}
{{< video https://www.youtube.com/watch?v=eSytQfqZsv8 >}}
:::

::: {style="max-width: 480px; margin: auto;"}
{{< video https://www.youtube.com/watch?v=YnXVAtzF4ss >}}
:::

::: {style="max-width: 480px; margin: auto;"}
{{< video https://www.youtube.com/watch?v=qr5JolEAuJU >}}
:::

## License

-   Slides and code examples © 2025 by the authors.
-   Code is MIT-licensed unless noted.

------------------------------------------------------------------------

### Maintainers & contact

For questions or issues, open a GitHub [issue](https://github.com/tq21/hal_short_course/issues) or email [sky.qiu\@berkeley.edu](mailto:sky.qiu@berkeley.edu).

------------------------------------------------------------------------
