---
title: "An example of the k-th order spline representation: k=2, d=3"
format: html
---

Consider the case that $d=3$ and $k=2$.
Then,
$$
\begin{eqnarray*}
Q(x)&=&\sum_{s_1\subset\{1,2,3\},\mid s_1\mid>0} \phi^1_0(x(s_1)) Q^{(1)}_{s_1}(0(s_1))\\
&&+\sum_{\bar{s}_2,\mid s_2\mid>0}\phi^1_0(x(s_1/s_2))\phi^2_0(x(s_2))Q^{(2)}_{\bar{s}(2)}(0(s_2))\\
&&+\sum_{\bar{s}(3), \mid s_3\mid>0}\phi^1_0(x(s_1/s_2))\phi_0^2(x(s_2/s_3))\int \phi^2_{u(s_3)}(x(s_3)) Q^{(2)}_{\bar{s}(3)}(du(s_3)).
\end{eqnarray*}
$$
Note that in this example, the parametric component of the model consists of two parts. The first part is the fully saturated interaction model, which includes the terms
$$
x_1,x_2,x_3,x_1x_2,x_1x_3,x_2x_3,x_1x_2x_3.
$$
The second component is a parametric model of the form $$
\sum_{s_1,s_2\subset s_1,\mid s_2\mid>0}\prod_{j\in s_1/s_2}x_j \prod_{j\in s_2}x_j^2.
$$
Let $(x-u)^2_+=I(x\geq u)(x-u)^2$. Now, we enumerate all terms from this second parametric part:

- When $s_1$ is a single-coordinate subset, we obtain:
$$
x_1^2,x_2^2,x_3^2;
$$

- When $s_1$ is a two-coordinate subset, with $s_2$ being either a single- or two-coordinate subset, we get:
$$
x_2x_1^2,x_1x_2^2,x_3x_1^2,x_1x_3^2,x_3x_2^2,x_2x_3^2,x_1^2x_2^2, x_1^2x_3^2,x_2^2x_3^2;
$$

- When $s_1=\{1,2,3\}$, and $s_2$ ranges over all non-empty subsets of $s_1$, the terms are:
$$
x_2x_3x_1^2,x_1x_3x_2^2,x_1x_2x_3^2,x_3x_1^2x_2^2,x_2x_1^2x_3^2,x_1x_2^2x_3^2,x_1^2x_2^2x_3^2.
$$

The infinite dimensional component includes a union over $s_3,\mid s_3\mid>0$ and $u(s_3)$ of a $(s_3,u(s_3))$-specific saturated interaction model given by
$$
\sum_{\{ (s_1,s_2): s_2\subset s_1,s_3\subset s_2}\prod_{j\in s_1/s_2}x_j\prod_{j\in s_2/s_3}x_j^2\prod_{j\in s_3}I(x_j>u)(x_j-u)^2.
$$
We now enumerate all terms from this infinite dimensional component:

- When $s_1=s_2=s_3$ are single-coordinate subsets:
$$
(x_1-u_1)_+^2,(x_2-u_2)_+^2,(x_3-u_3)_+^2;
$$

- When $s_1=\{1,2\}$:
$$
x_2(x_1-u_1)_+^2,x_1(x_2-u_2)_+^2,x_2^2(x_1-u_1)_+^2,x_1^2(x_2-u_2)_+^2,(x_1-u_1)_+^2(x_2-u_2)_+^2;
$$

- When $s_1=\{1,3\}$:
$$
x_3(x_1-u_1)_+^2,x_1(x_3-u_3)_+^2,x_3^2(x_1-u_1)_+^2,x_1^2(x_3-u_3)_+^2,(x_1-u_1)_+^2(x_3-u_3)_+^2;
$$

- When $s_1=\{2,3\}$:
$$
x_3(x_2-u_2)_+^2,x_2(x_3-u_3)_+^2,x_3^2(x_2-u_2)_+^2,x_2^2(x_3-u_3)_+^2,(x_2-u_2)_+^2(x_3-u_3)_+^2;
$$

- When $s_1=\{1,2,3\}$, and $s_2=s_3$ are both single-coordinate subsets:
$$
x_2x_3(x_1-u_1)_+^2,x_1x_3(x_2-u_2)_+^2,x_1x_2(x_3-u_3)_+^2;
$$

- When $s_1=\{1,2,3\}$, and $s_2=\{1,2\}$:
$$
x_2x_2^2(x_1-u_1)_+^2,x_3x_1^2(x_2-u_2)_+^2,x_3(x_1-u_1)_+^2(x_2-u_2)_+^2;
$$

- When $s_1=\{1,2,3\}$, and $s_2=\{1,3\}$:
$$
x_3x_2^2(x_1-u_1)_+^2,x_3x_1^2(x_3-u_3)_+^2,x_3(x_1-u_1)_+^2(x_3-u_3)_+^2;
$$

- When $s_1=\{1,2,3\}$, and $s_2=\{2,3\}$:
$$
x_3x_2^2(x_2-u_2)_+^2,x_3x_2^2(x_3-u_3)_+^2,x_3(x_2-u_2)_+^2(x_3-u_3)_+^2;
$$

- Finally, when $s_1=s_2=\{1,2,3\}$:
$$
\begin{gather*}
x_2^2x_3^2(x_1-u_1)_+^2,x_1^2x_3^2(x_2-u_2)_+^2,x_1^2x_2^2(x_3-u_3)_+^2\\
x_3^2(x_1-u_1)_+^2(x_2-u_2)_+^2,x_2^2(x_1-u_1)_+^2(x_3-u_3)_+^2,x_1^2(x_2-u_2)_+^2(x_3-u_3)_+^2\\
(x_1-u_1)_+^2(x_2-u_2)_+^2(x_3-u_3)_+^2.
\end{gather*}
$$
